import AddToDo from "@/components/AddToDo/AddToDo";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>ToDo || Daily Task Application</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-w-7xl m-auto py-4">
        <AddToDo />
      </main>
    </>
  );
}
